# Generated by Django 4.1.3 on 2023-12-24 21:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('hash', models.CharField(db_index=True, max_length=64, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(64)])),
                ('height', models.PositiveIntegerField(db_index=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('prev_hash', models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.MinLengthValidator(64)])),
                ('nr_inputs', models.PositiveIntegerField(default=0)),
                ('nr_outputs', models.PositiveIntegerField(default=0)),
                ('nr_kernels', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('default', models.BooleanField(default=False)),
                ('fetch_price', models.BooleanField(default=True)),
                ('load_progress', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NodeGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reorg',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('blockchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorgs', to='api.blockchain')),
                ('end_reorg_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_reorgs', to='api.block')),
                ('start_main_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_mains', to='api.block')),
                ('start_reorg_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_reorgs', to='api.block')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('output_type', models.TextField(choices=[('Transaction', 'Transaction'), ('Coinbase', 'Coinbase')])),
                ('commitment', models.CharField(db_index=True, max_length=66)),
                ('spent', models.BooleanField()),
                ('proof', models.TextField()),
                ('proof_hash', models.CharField(max_length=64)),
                ('merkle_proof', models.TextField(null=True)),
                ('mmr_index', models.IntegerField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='api.block')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('api_url', models.URLField()),
                ('api_username', models.CharField(max_length=255)),
                ('api_password', models.CharField(max_length=255)),
                ('archive', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='api.nodegroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kernel',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('features', models.TextField()),
                ('fee', models.BigIntegerField()),
                ('fee_shift', models.IntegerField()),
                ('lock_height', models.IntegerField()),
                ('excess', models.CharField(db_index=True, max_length=66)),
                ('excess_sig', models.CharField(max_length=142)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kernels', to='api.block')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('commitment', models.CharField(db_index=True, max_length=66)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='api.block')),
                ('output', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='api.output')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DramatiqTask',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('bootstrap', 'Bootstrap'), ('blockchain_delete', 'Blockchain delete')], max_length=255)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('skipped', 'Skipped'), ('success', 'Success'), ('failure', 'Failure')], max_length=255)),
                ('failure_reason', models.TextField(default=None, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlockHeader',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
                ('kernel_root', models.CharField(max_length=64)),
                ('output_root', models.CharField(max_length=64)),
                ('range_proof_root', models.CharField(max_length=64)),
                ('kernel_mmr_size', models.IntegerField()),
                ('output_mmr_size', models.IntegerField()),
                ('nonce', models.TextField()),
                ('edge_bits', models.IntegerField()),
                ('cuckoo_solution', models.TextField(db_index=True)),
                ('secondary_scaling', models.IntegerField()),
                ('total_difficulty', models.BigIntegerField()),
                ('total_kernel_offset', models.CharField(max_length=64)),
                ('blockchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headers', to='api.blockchain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='blockchain',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blockchains', to='api.node'),
        ),
        migrations.AddField(
            model_name='block',
            name='blockchain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='api.blockchain'),
        ),
        migrations.AddField(
            model_name='block',
            name='header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block', to='api.blockheader'),
        ),
        migrations.AddField(
            model_name='block',
            name='reorg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='api.reorg'),
        ),
    ]
